
/* Drop Tables */

DROP TABLE JF_DIARYS CASCADE CONSTRAINTS;
DROP TABLE JF_EVENTS CASCADE CONSTRAINTS;
DROP TABLE JF_MYTHEATERS CASCADE CONSTRAINTS;
DROP TABLE JF_QUESTIONS CASCADE CONSTRAINTS;
DROP TABLE JF_RESERVATIONS CASCADE CONSTRAINTS;
DROP TABLE JF_REVIEWS CASCADE CONSTRAINTS;
DROP TABLE JF_WISHLISTS CASCADE CONSTRAINTS;
DROP TABLE JF_MEMBERS CASCADE CONSTRAINTS;
DROP TABLE JF_SCREENINGS CASCADE CONSTRAINTS;
DROP TABLE JF_MOVIES CASCADE CONSTRAINTS;
DROP TABLE JF_NOTICES CASCADE CONSTRAINTS;
DROP TABLE JF_SCREENING_ROOMS CASCADE CONSTRAINTS;
DROP TABLE JF_THEATERS CASCADE CONSTRAINTS;



/* Drop Sequences */

DROP SEQUENCE jf_diary_seq;
DROP SEQUENCE jf_event_seq;
DROP SEQUENCE jf_movies_seq;
DROP SEQUENCE jf_mytheater_seq;
DROP SEQUENCE jf_notice_seq;
DROP SEQUENCE jf_qna_seq;
DROP SEQUENCE jf_res_seq;
DROP SEQUENCE jf_review_seq;
DROP SEQUENCE jf_room_seq;
DROP SEQUENCE jf_screening_seq;
DROP SEQUENCE jf_theater_seq;
DROP SEQUENCE jf_wishlist_seq;




/* Create Sequences */

-- 다이어리 번호
CREATE SEQUENCE jf_diary_seq;
-- 이벤트 번호
CREATE SEQUENCE jf_event_seq;
-- 영화번호
CREATE SEQUENCE jf_movies_seq;
-- 자주가는극장번호
CREATE SEQUENCE jf_mytheater_seq;
-- 공지 번호
CREATE SEQUENCE jf_notice_seq;
-- 질문번호
CREATE SEQUENCE jf_qna_seq;
-- 예매번호
CREATE SEQUENCE jf_res_seq;
-- 리뷰 번호
CREATE SEQUENCE jf_review_seq;
-- 상영관 번호
CREATE SEQUENCE jf_room_seq;
-- 상영번호
CREATE SEQUENCE jf_screening_seq;
-- 극장 번호
CREATE SEQUENCE jf_theater_seq;
-- 위시리스트 번호
CREATE SEQUENCE jf_wishlist_seq;



/* Create Tables */

CREATE TABLE JF_DIARYS
(
	DIARY_NO number(4,0) NOT NULL,
	DIARY_CONTENTS varchar2(4000),
	DIARY_CREATE_DATE date,
	MEMBER_ID varchar2(100) NOT NULL,
	DIARY_FRIEND varchar2(80),
	DIARY_TRAILER varchar2(1000),
	DIARY_STEEL_CUT varchar2(1000),
	DIARY_MOVIE_DETAIL_NO number(20),
	DIARY_PHOTO varchar2(1000),
	PRIMARY KEY (DIARY_NO)
);


CREATE TABLE JF_EVENTS
(
	EVENT_NO number(4,0) NOT NULL,
	EVENT_TITLE varchar2(2000),
	EVENT_IMG_NAME varchar2(500),
	EVENT_START_DATE date,
	EVENT_END_DATE date,
	EVENT_CATEGORY varchar2(50),
	EVENT_CONTENT varchar2(500),
	PRIMARY KEY (EVENT_NO)
);


CREATE TABLE JF_MEMBERS
(
	MEMBER_ID varchar2(100) NOT NULL,
	MEMBER_PWD char(40) NOT NULL,
	MEMBER_NAME varchar2(20) NOT NULL,
	MEMBER_NICKNAME varchar2(200),
	MEMBER_PHONE varchar2(20),
	MEMBER_EMAIL varchar2(300),
	MEMBER_BIRTH date,
	MEMBER_GENDER char(6),
	MEMEBER_POINT number(5,0) DEFAULT 0,
	MEMBER_CREATE_DATE date DEFAULT SYSDATE,
	MEMBER_TYPE varchar2(40) DEFAULT 'USER',
	MEMBER_USED_YN char(1),
	MEMBER_HINT varchar2(100),
	PRIMARY KEY (MEMBER_ID)
);


CREATE TABLE JF_MOVIES
(
	MOVIE_NO number(5,0) NOT NULL,
	MOVIE_KORTITLE varchar2(500) NOT NULL,
	MOVIE_ENGTITLE varchar2(500) NOT NULL,
	MOVIE_RESERVATION_RATE number(4,1),
	MOVIE_GPA number(2,0),
	MOVIE_REAL_MEMBERS number(9),
	MOVIE_DIRECTOR varchar2(100),
	MOVIE_GENRE varchar2(100),
	MOVIE_AGE_LIMIT number(2,0),
	MOVIE_RUNNING_TIME number(3,0),
	MOVIE_PROD_COUNTRY varchar2(100),
	MOVIE_RELEASE_DATE date,
	MOVIE_WISHLIST number(7,0),
	MOVIE_INFO varchar2(4000),
	MOVIE_TRAILER varchar2(1000),
	MOVIE_STEEL_CUT varchar2(1000),
	MOVIE_SCREEN_YN char(1),
	MOVIE_PRICE number(5,0),
	MOVIE_ACTORS varchar2(500),
	MOVIE_POSTER varchar2(2000),
	MOVIE_CREATE_DATE date,
	MOVIE_GOLDENEGG number(3,0) DEFAULT 0,
	PRIMARY KEY (MOVIE_NO)
);


CREATE TABLE JF_MYTHEATERS
(
	MYTHEATER_NO number(3,0) NOT NULL,
	MYTHEATER_CREATE_DATE date DEFAULT SYSDATE,
	MEMBER_ID varchar2(100) NOT NULL,
	THEATER_NO number(3,0) NOT NULL,
	MYTHEATER_USED_YN char(1) DEFAULT 'Y',
	PRIMARY KEY (MYTHEATER_NO)
);


CREATE TABLE JF_NOTICES
(
	NOTICE_NO number(4,0) NOT NULL,
	NOTICE_TITLE varchar2(1000),
	NOTICE_CONTENT varchar2(4000),
	NOTICE_CREATE_DATE date,
	NOTICE_VIEWS number(7,0),
	PRIMARY KEY (NOTICE_NO)
);


CREATE TABLE JF_QUESTIONS
(
	QUESTION_NO number(5,0) NOT NULL,
	QUESTION_TITLE varchar2(1000),
	-- 
	-- 
	QUESTION_CREATE_DATE date DEFAULT SYSDATE,
	QUESTION_STATUS varchar2(20),
	THEATER_NO number(3,0) NOT NULL,
	ANSWER_CONTENT varchar2(4000),
	ANSWER_CREATE_DATE date,
	MEMBER_ID varchar2(100) NOT NULL,
	QUESTION_CONTENT varchar2(4000),
	PRIMARY KEY (QUESTION_NO)
);


CREATE TABLE JF_RESERVATIONS
(
	RESERVATION_NO number(4,0) NOT NULL,
	MEMBER_ID varchar2(100) NOT NULL,
	SCREENING_NO number(4,0) NOT NULL,
	RESERVATION_DATE date,
	RESERVATION_YN char(1),
	RESERVATION_COUNT number(3,0),
	PRIMARY KEY (RESERVATION_NO)
);


CREATE TABLE JF_REVIEWS
(
	REVIEW_NO number(4,0) NOT NULL,
	REVIEW_GPA number(2,0),
	REVIEW_COMMENT varchar2(2000),
	REVIEW_PRODUCTION number(1),
	REVIEW_OST number(1),
	REVIEW_STORY number(1),
	REVIEW_ACTOR number(1),
	REVIEW_BEAUTY number(1),
	MEMBER_ID varchar2(100) NOT NULL,
	MOVIE_NO number(5,0) NOT NULL,
	REVIEW_CREATE_DATE date DEFAULT sysdate,
	REVIEW_LIKES number(5,0) DEFAULT 0,
	PRIMARY KEY (REVIEW_NO)
);


CREATE TABLE JF_SCREENINGS
(
	SCREENING_NO number(4,0) NOT NULL,
	SCREENING_DATE date,
	SCREENING_TIME varchar2(100),
	ROOM_NO number(4,0) NOT NULL,
	MOVIE_NO number(5,0) NOT NULL,
	PRIMARY KEY (SCREENING_NO)
);


CREATE TABLE JF_SCREENING_ROOMS
(
	ROOM_NO number(4,0) NOT NULL,
	ROOM_NAME varchar2(200),
	ROOM_SEAT number(4,0),
	THEATER_NO number(3,0) NOT NULL,
	PRIMARY KEY (ROOM_NO)
);


CREATE TABLE JF_THEATERS
(
	THEATER_NO number(3,0) NOT NULL,
	THEATER_NAME varchar2(100),
	THEATER_LOCATION varchar2(2000),
	THEATER_TEL varchar2(20) DEFAULT '1544-1122',
	THEATER_ROOM number(2,0),
	THEATER_SEAT number(4,0),
	THEATER_TRAFFIC_INFO varchar2(4000),
	THEATER_PARKING_INFO varchar2(4000),
	THEATER_CITY varchar2(30),
	THEATER_PHOTO varchar2(1000),
	PRIMARY KEY (THEATER_NO)
);


CREATE TABLE JF_WISHLISTS
(
	WISHLIST_YN char(1),
	WISHLISTS_NO number(4,0) NOT NULL,
	MEMBER_ID varchar2(100) NOT NULL,
	MOVIE_NO number(5,0) NOT NULL,
	PRIMARY KEY (WISHLISTS_NO)
);



/* Create Foreign Keys */

ALTER TABLE JF_DIARYS
	ADD FOREIGN KEY (MEMBER_ID)
	REFERENCES JF_MEMBERS (MEMBER_ID)
;


ALTER TABLE JF_MYTHEATERS
	ADD FOREIGN KEY (MEMBER_ID)
	REFERENCES JF_MEMBERS (MEMBER_ID)
;


ALTER TABLE JF_QUESTIONS
	ADD FOREIGN KEY (MEMBER_ID)
	REFERENCES JF_MEMBERS (MEMBER_ID)
;


ALTER TABLE JF_RESERVATIONS
	ADD FOREIGN KEY (MEMBER_ID)
	REFERENCES JF_MEMBERS (MEMBER_ID)
;


ALTER TABLE JF_REVIEWS
	ADD FOREIGN KEY (MEMBER_ID)
	REFERENCES JF_MEMBERS (MEMBER_ID)
;


ALTER TABLE JF_WISHLISTS
	ADD FOREIGN KEY (MEMBER_ID)
	REFERENCES JF_MEMBERS (MEMBER_ID)
;


ALTER TABLE JF_REVIEWS
	ADD FOREIGN KEY (MOVIE_NO)
	REFERENCES JF_MOVIES (MOVIE_NO)
;


ALTER TABLE JF_SCREENINGS
	ADD FOREIGN KEY (MOVIE_NO)
	REFERENCES JF_MOVIES (MOVIE_NO)
;


ALTER TABLE JF_WISHLISTS
	ADD FOREIGN KEY (MOVIE_NO)
	REFERENCES JF_MOVIES (MOVIE_NO)
;


ALTER TABLE JF_RESERVATIONS
	ADD FOREIGN KEY (SCREENING_NO)
	REFERENCES JF_SCREENINGS (SCREENING_NO)
;


ALTER TABLE JF_SCREENINGS
	ADD FOREIGN KEY (ROOM_NO)
	REFERENCES JF_SCREENING_ROOMS (ROOM_NO)
;


ALTER TABLE JF_MYTHEATERS
	ADD FOREIGN KEY (THEATER_NO)
	REFERENCES JF_THEATERS (THEATER_NO)
;


ALTER TABLE JF_QUESTIONS
	ADD FOREIGN KEY (THEATER_NO)
	REFERENCES JF_THEATERS (THEATER_NO)
;


ALTER TABLE JF_SCREENING_ROOMS
	ADD FOREIGN KEY (THEATER_NO)
	REFERENCES JF_THEATERS (THEATER_NO)
;



/* Comments */

COMMENT ON COLUMN JF_QUESTIONS.QUESTION_CREATE_DATE IS '
';



